### PR TITLE
Improve effect

### PR DESCRIPTION
**Pull request by dskiba**
There is no need to create function each time when history changes and do not use it.

### CODE REVIEW

**Comment by shirshak55** [comment]
Sadly author doesn't accept any PR. I wonder if there is any maintained fork.

"I will not be accepting PR's on this repository. Feel free to fork and maintain your own version."

**Comment by hayuna** [comment]
You can try with @leopere

https://github.com/Leopere/jira_clone

**Comment by Leopere** [comment]
I'll adopt the project yes sure.  I wonder if @oldboyxx would be willing to post the alternative in the CONTRIBUTING.md

**Comment by Leopere** [comment]
https://github.com/Leopere/jira_clone/pull/1

**Comment by Leopere** [comment]
Updated URL and GitHub Org https://github.com/FauxJira/FauxJira because it sounded clever I guess.

**Comment by shirshak55** [comment]
@Leopere yea looks good. I just think if author add if u want to contribute go to this fork would be better in readme or somewhere?

**Comment by Leopere** [comment]
@oldboyxx I'd spun up a fork in case someone wanted to contribute. If you want people to redirect their contributions to https://github.com/FauxJira/FauxJira we'll give it a try.

**Comment by re-thc** [comment]
If this project is to work out, please don't use the name Jira or a reference to it as part of the "brand". It's trademarked. Any time it does become popular and it'd likely get taken down.

**Comment by shirshak55** [comment]
yea lets think some creative names. Flare, cyclone, fusion, nitro would be my recommendation.

**Comment by Leopere** [comment]
You can parody names and trademarks. But you’re right.

**Pull request closed without merging**
